package poo.jogo.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.time.Clock;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import poo.jogo.entidades.Banca;
import poo.jogo.entidades.Jogador;
import poo.jogo.entidades.interf.BancaInterface;

/**
 *
 * @author thoma
 */
public class GuiInicial extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form guiInicial
     */
    public GuiInicial() {
    	this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantidadeJogadores = new javax.swing.JComboBox<>();
        textJogador2 = new javax.swing.JTextField();
        textJogador3 = new javax.swing.JTextField();
        textJogador1 = new javax.swing.JTextField();
        textJogador4 = new javax.swing.JTextField();
        textJogador5 = new javax.swing.JTextField();
        textJogador6 = new javax.swing.JTextField();
        textJogador7 = new javax.swing.JTextField();
        jButtonJogar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 860));



        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lTitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("BlackJack - UPE Caruaru");
        getContentPane().add(lTitulo);
        lTitulo.setBounds(340, 90, 740, 114);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informe a quantidade de jogadores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 240, 284, 17);

        quantidadeJogadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        quantidadeJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeJogadoresActionPerformed(evt);
            }
        });
        getContentPane().add(quantidadeJogadores);
        quantidadeJogadores.setBounds(650, 240, 50, 30);

        textJogador2.setText("Jogador 2");
        textJogador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador2MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador2);
        textJogador2.setBounds(360, 340, 360, 30);

        textJogador3.setText("Jogador 3");
        textJogador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador3MouseClicked(evt);
            }
        });
        textJogador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJogador3ActionPerformed(evt);
            }
        });
        getContentPane().add(textJogador3);
        textJogador3.setBounds(360, 380, 360, 30);

        textJogador1.setText("Jogador 1");
        textJogador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador1MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador1);
        textJogador1.setBounds(360, 300, 360, 30);

        textJogador4.setText("Jogador 4");
        textJogador4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador4MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador4);
        textJogador4.setBounds(360, 420, 360, 30);

        textJogador5.setText("Jogador 5");
        textJogador5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador5MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador5);
        textJogador5.setBounds(360, 460, 360, 30);

        textJogador6.setText("Jogador 6");
        textJogador6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador6MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador6);
        textJogador6.setBounds(360, 500, 360, 30);

        textJogador7.setText("Jogador 7");
        textJogador7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJogador7MouseClicked(evt);
            }
        });
        getContentPane().add(textJogador7);
        textJogador7.setBounds(360, 540, 360, 30);

        jButtonJogar.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jButtonJogar.setText("JOGAR!!!");
        jButtonJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jButtonJogarMouseClicked(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        getContentPane().add(jButtonJogar);
        jButtonJogar.setBounds(1020, 340, 180, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("..\\Imagem do Jogo\\table.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1024, 860));
        jLabel2.setMinimumSize(new java.awt.Dimension(1024, 860));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 860);
        




        pack();
    }// </editor-fold>                        

    private void textJogador3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textJogador1MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador1.setText("");
    }                                         

    private void textJogador2MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador2.setText("");
    }                                         

    private void textJogador3MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador3.setText("");
    }                                         

    private void textJogador4MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador4.setText("");
    }                                         

    private void textJogador5MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador5.setText("");
    }                                         

    private void textJogador6MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador6.setText("");
    }                                         

    private void textJogador7MouseClicked(java.awt.event.MouseEvent evt) {                                          
        this.textJogador7.setText("");
    }                                         

    private void jButtonJogarMouseClicked(java.awt.event.MouseEvent evt) throws Exception { //CHAMA TUDOOOOOOOO - AQUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
        while (true) {
        	BancaInterface banca = null;
    		banca = new Banca("BANCA", 5000);
        	JTextField lista[] = {textJogador1,textJogador2,textJogador3,textJogador4,textJogador5,textJogador6,textJogador7};
            int cont = this.quantidadeJogadores.getSelectedIndex() + 1;
            String texto = "textJogador";
            for (int i = 0; i < cont; i++){
                System.out.println(lista[i].getText());
                banca.obterJogadores(new Jogador(lista[i].getText(), 1000));
                
            }
        	banca.iniciarV(cont);
        	this.dispose();
        	Object[] escolhas = {"SIM", "NÃO"};
    		int index = JOptionPane.showOptionDialog(null,"Você deseja jogar novamente?", "Jogar novamente", 0, JOptionPane.QUESTION_MESSAGE, null, escolhas, 1);
    		if (index == 1 || index == JOptionPane.CLOSED_OPTION) {
    			break;
    		}
    		
        }
        
        this.setVisible(true);
        
    }                                        

    private void quantidadeJogadoresActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        JTextField lista[] = {textJogador1,textJogador2,textJogador3,textJogador4,textJogador5,textJogador6,textJogador7};
        int i = 0;
        for (i = 0; i <= this.quantidadeJogadores.getSelectedIndex(); i++){
            lista[i].setVisible(true);
        }
        for (int j = i; j < 7; j++){
            lista[j].setVisible(false);
        }
    }                                                   

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        JTextField lista[] = {textJogador1,textJogador2,textJogador3,textJogador4,textJogador5,textJogador6,textJogador7};
        for (int j = 1; j < 7; j++){
            lista[j].setVisible(false);
        }
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInicial().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JComboBox<String> quantidadeJogadores;
    private javax.swing.JTextField textJogador1;
    private javax.swing.JTextField textJogador2;
    private javax.swing.JTextField textJogador3;
    private javax.swing.JTextField textJogador4;
    private javax.swing.JTextField textJogador5;
    private javax.swing.JTextField textJogador6;
    private javax.swing.JTextField textJogador7;
    // End of variables declaration                   
    private  JTextField lista[] = {textJogador1,textJogador2,textJogador3,textJogador4,textJogador5,textJogador6,textJogador7};
}
